spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/openpipedata?&allowMultiQueries=true&characterEncoding=utf-8
    username: "root"
    password: "qq123123"

logging:
  level:
    datart:
      core:
        mappers: info
      data.provider.jdbc: info
  config: config/logback.xml

management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: '*'

springdoc:
  version: '0.1'
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  group-configs:
    - group: stores
      paths-to-match: /store/**
  cache:
    disabled: true


server:
  port: 8081
  forward-headers-strategy: framework


openPipe:
  server:
    path-prefix:
      #token配置
#open-pipe:
#  token:
#        #是否有状态
#        state: false
#        #是否单用户登录
#        single: false
#        #单用户登录范围
#        single-level: all
#        #token签名
#        #使用 @org.springblade.test.SignKeyGenerator 获取
#        sign-key: 请配置32位签名

shiro:
  web:
    enabled: true